Repository CMU-17-356/dronuts2022-group-6, pull requests merged in 2022-02, with the labels that each got.

#12 starting odm creation
  wiki/object-data-model.json
Labels: should have

#15 Restructure
  app/backend/src/app.ts
  app/backend/test/app.test.ts
  wiki/object-data-model.json
Labels: documentation, should have

#13 object data model (1/2) and examples
  wiki/object-data-model.json
Labels: documentation

#21 Olly dev
  .gitignore
  dronuts-react/package.json
  dronuts-react/public/index.html
  dronuts-react/src/App.tsx
  dronuts-react/src/assets/DronutsLogo.png
  dronuts-react/src/assets/donut-temp.png
  dronuts-react/src/components/common/cart-card.css
  dronuts-react/src/components/common/cart-card.tsx
  dronuts-react/src/components/common/cart.css
  dronuts-react/src/components/common/cart.tsx
  dronuts-react/src/components/common/donut-card.css
  dronuts-react/src/components/common/donut-card.tsx
  dronuts-react/src/components/common/nav.css
  dronuts-react/src/components/common/nav.tsx
  dronuts-react/src/components/pages/explore.tsx
  dronuts-react/src/components/pages/home.css
  dronuts-react/src/components/pages/home.tsx
  dronuts-react/src/index.tsx
  package-lock.json
  package.json
Labels: should have

#19 Taco schema
  app/backend/schema/addressSchema.ts
  app/backend/schema/customerSchema.ts
  app/backend/schema/donutSchema.ts
  app/backend/schema/droneSchema.ts
  app/backend/schema/employeeSchema.ts
  package-lock.json
  package.json
  wiki/object-data-model.json
Labels: should have

#44 Mongoose
  .gitignore
  app/babel.config.js
  app/backend/src/app.ts
  app/backend/test/schema/orderItemsSchema.test.ts
  app/backend/test/schema/orderSchema.test.ts
  app/coverage/clover.xml
  app/coverage/coverage-final.json
  app/coverage/lcov-report/base.css
  app/coverage/lcov-report/block-navigation.js
  app/coverage/lcov-report/customerSchema.ts.html
  app/coverage/lcov-report/donutSchema.ts.html
  app/coverage/lcov-report/droneSchema.ts.html
  app/coverage/lcov-report/employeeSchema.ts.html
  app/coverage/lcov-report/favicon.png
  app/coverage/lcov-report/index.html
  app/coverage/lcov-report/orderItemsSchema.ts.html
  app/coverage/lcov-report/orderSchema.ts.html
  app/coverage/lcov-report/prettify.css
  app/coverage/lcov-report/prettify.js
  app/coverage/lcov-report/sort-arrow-sprite.png
  app/coverage/lcov-report/sorter.js
  app/coverage/lcov.info
  app/jest.config.ts
  app/package-lock.json
  app/package.json
  app/schema/addressSchema.ts
  app/schema/customerSchema.ts
  app/schema/donutSchema.ts
  app/schema/droneSchema.ts
  app/schema/employeeSchema.ts
  app/schema/orderItemsSchema.ts
  app/schema/orderSchema.ts
  app/src/app.ts
  app/src/mongoosedb.ts
  app/src/order.ts
  app/src/orderItem.ts
  app/tests/schema/customerSchema.test.ts
  app/tests/schema/donutSchema.test.ts
  app/tests/schema/droneSchema.test.ts
  app/tests/schema/employeeSchema.test.ts
  app/tests/schema/orderItemsSchema.test.ts
  app/tests/schema/orderSchema.test.ts
  app/tests/src/app.test.ts
  app/tsconfig.json
Labels: enhancement

#45 partially updated readme and git ignore
  .gitignore
  README.md
  app/coverage/clover.xml
  app/coverage/coverage-final.json
  app/coverage/lcov-report/base.css
  app/coverage/lcov-report/block-navigation.js
  app/coverage/lcov-report/customerSchema.ts.html
  app/coverage/lcov-report/donutSchema.ts.html
  app/coverage/lcov-report/droneSchema.ts.html
  app/coverage/lcov-report/employeeSchema.ts.html
  app/coverage/lcov-report/favicon.png
  app/coverage/lcov-report/index.html
  app/coverage/lcov-report/orderItemsSchema.ts.html
  app/coverage/lcov-report/orderSchema.ts.html
  app/coverage/lcov-report/prettify.css
  app/coverage/lcov-report/prettify.js
  app/coverage/lcov-report/sort-arrow-sprite.png
  app/coverage/lcov-report/sorter.js
  app/coverage/lcov.info
  app/package.json
  app/src/app.ts
  app/src/mongoosedb.ts
  dist/app.js
  dist/app.js.map
  dronuts-react/package-lock.json
  package-lock.json
  package.json
Labels: documentation
